# Generated by Django 4.0 on 2022-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='nome_do_meio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
